apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-staging
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-staging
    app.kubernetes.io/part-of: partner-catalog-staging
  name: partner-catalog-staging
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-staging
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-staging
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/beaumorley-tenant/partner-catalog-staging/partner-catalog-staging@sha256:0d8d7359bac7f9490be87872394275508a12ef05aa12c42b6fb15d423a1e12d2
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
