apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-staging
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/beaumorley-tenant/partner-catalog-staging/partner-catalog-staging@sha256:3d94ba280e9da01741f1de24b517be036814aad34ecc2fe937362dc3a8fb9752
        name: my-java-springboot
        resources: {}
status: {}
